# Generated by Django 5.2.5 on 2025-08-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerai', '0003_career_delete_careerrecommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjects', models.CharField(max_length=255)),
                ('career', models.CharField(max_length=255)),
                ('career_description', models.TextField()),
                ('career_opportunities', models.TextField()),
                ('sl_monthly_salary', models.CharField(max_length=50)),
                ('sl_location', models.CharField(max_length=100)),
                ('foreign_monthly_salary', models.CharField(max_length=50)),
                ('foreign_location', models.CharField(max_length=100)),
                ('work_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Career',
        ),
    ]
