# Generated by Django 5.2.5 on 2025-08-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerai', '0004_careerrecommendation_delete_career'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerrecommendation',
            name='career',
            field=models.CharField(default='Not specified', max_length=255),
        ),
        migrations.AlterField(
            model_name='careerrecommendation',
            name='career_description',
            field=models.TextField(default='Not specified'),
        ),
        migrations.AlterField(
            model_name='careerrecommendation',
            name='career_opportunities',
            field=models.TextField(default='Not specified'),
        ),
        migrations.AlterField(
            model_name='careerrecommendation',
            name='foreign_location',
            field=models.CharField(default='Not specified', max_length=255),
        ),
        migrations.AlterField(
            model_name='careerrecommendation',
            name='foreign_monthly_salary',
            field=models.CharField(default='Not specified', max_length=100),
        ),
        migrations.AlterField(
            model_name='careerrecommendation',
            name='sl_location',
            field=models.CharField(default='Not specified', max_length=255),
        ),
        migrations.AlterField(
            model_name='careerrecommendation',
            name='sl_monthly_salary',
            field=models.CharField(default='Not specified', max_length=100),
        ),
        migrations.AlterField(
            model_name='careerrecommendation',
            name='subjects',
            field=models.CharField(default='Not specified', max_length=255),
        ),
        migrations.AlterField(
            model_name='careerrecommendation',
            name='work_type',
            field=models.CharField(default='Not specified', max_length=100),
        ),
    ]
