# Generated by Django 5.2.5 on 2025-08-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerai', '0005_alter_careerrecommendation_career_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerrecommendation',
            name='career',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='careerrecommendation',
            name='career_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='careerrecommendation',
            name='career_opportunities',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='careerrecommendation',
            name='foreign_location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='careerrecommendation',
            name='foreign_monthly_salary',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='careerrecommendation',
            name='sl_location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='careerrecommendation',
            name='sl_monthly_salary',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='careerrecommendation',
            name='subjects',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='careerrecommendation',
            name='work_type',
            field=models.CharField(max_length=100),
        ),
    ]
