# Generated by Django 5.2.5 on 2025-08-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerai', '0007_career_delete_careerrecommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='work_type',
            field=models.CharField(max_length=50),
        ),
    ]
