# Generated by Django 5.2.5 on 2025-08-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerai', '0011_careerrecommendation_delete_career'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('career_opportunities', models.TextField()),
                ('sl_monthly_salary', models.CharField(max_length=100)),
                ('sl_location', models.CharField(max_length=255)),
                ('foreign_monthly_salary', models.CharField(max_length=100)),
                ('foreign_location', models.CharField(max_length=255)),
                ('work_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='CareerRecommendation',
        ),
    ]
