# Generated by Django 5.2.5 on 2025-09-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerai', '0013_careerrecommendation_delete_career'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerrecommendation',
            name='education_requirement',
            field=models.TextField(default='Not specified'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='careerrecommendation',
            name='skills',
            field=models.TextField(default='Not specified'),
            preserve_default=False,
        ),
    ]
